METADATA_DB_URL = "ALPHATRION_METADATA_DB_URL"
ARTIFACT_REGISTRY_URL = "ALPHATRION_ARTIFACT_REGISTRY_URL"
ENABLE_ARTIFACT_STORAGE = "ALPHATRION_ENABLE_ARTIFACT_STORAGE"
ENABLE_TRACING = "ALPHATRION_ENABLE_TRACING"
