"""remove step from trial

Revision ID: 03410247c6b7
Revises: c89fc8504699
Create Date: 2026-01-16 15:17:18.057002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03410247c6b7'
down_revision: Union[str, Sequence[str], None] = 'c89fc8504699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'step')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
