"""add duration for run

Revision ID: 203ea6f694b7
Revises: f23c33ff866a
Create Date: 2026-03-02 21:01:24.249403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203ea6f694b7'
down_revision: Union[str, Sequence[str], None] = 'f23c33ff866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('duration', sa.Float(), nullable=True, comment='Duration of the run in seconds'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'duration')
    # ### end Alembic commands ###
