"""init

Revision ID: 56a7bb45d6b0
Revises: 
Create Date: 2025-11-26 15:01:29.357153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a7bb45d6b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trials', 'status',
               existing_type=sa.INTEGER(),
               comment='Status of the trial, 0: PENDING, 1: RUNNING, 9: COMPLETED, 10: FAILED',
               existing_comment='Status of the trial',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trials', 'status',
               existing_type=sa.INTEGER(),
               comment='Status of the trial',
               existing_comment='Status of the trial, 0: PENDING, 1: RUNNING, 9: COMPLETED, 10: FAILED',
               existing_nullable=False)
    # ### end Alembic commands ###
