"""remove trial_id

Revision ID: 85a1be1592e4
Revises: 264cf17e65e0
Create Date: 2026-03-02 00:18:09.675522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a1be1592e4'
down_revision: Union[str, Sequence[str], None] = '264cf17e65e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_snapshots_trial_id'), table_name='content_snapshots')
    op.drop_index(op.f('ix_content_snapshots_trial_id_is_del'), table_name='content_snapshots')
    op.drop_column('content_snapshots', 'trial_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_snapshots', sa.Column('trial_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_content_snapshots_trial_id_is_del'), 'content_snapshots', ['trial_id', 'is_del'], unique=False)
    op.create_index(op.f('ix_content_snapshots_trial_id'), 'content_snapshots', ['trial_id'], unique=False)
    # ### end Alembic commands ###
