"""change project id to team id

Revision ID: c2eb3f1f9b97
Revises: 85a1be1592e4
Create Date: 2026-03-02 01:34:57.018200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2eb3f1f9b97'
down_revision: Union[str, Sequence[str], None] = '85a1be1592e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_snapshots', sa.Column('team_id', sa.UUID(), nullable=False))
    op.drop_column('content_snapshots', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_snapshots', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('content_snapshots', 'team_id')
    # ### end Alembic commands ###
