"""Add team_members

Revision ID: c8d218b05082
Revises: 4c0afbe0b21c
Create Date: 2026-02-09 19:32:54.816854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8d218b05082'
down_revision: Union[str, Sequence[str], None] = '4c0afbe0b21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_metric', 'metrics', ['run_id', 'key'])
    op.drop_column('team_members', 'is_del')
    op.drop_column('team_members', 'meta')
    op.drop_column('users', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('team_members', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional metadata for the membership (e.g., role, permissions)'))
    op.add_column('team_members', sa.Column('is_del', sa.INTEGER(), autoincrement=False, nullable=True, comment='0 for not deleted, 1 for deleted'))
    op.drop_constraint('idx_unique_metric', 'metrics', type_='unique')
    # ### end Alembic commands ###
