"""Add snapshot tables

Revision ID: e35d91c5a67d
Revises: 344adc5da83a
Create Date: 2026-03-01 12:45:14.803440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35d91c5a67d'
down_revision: Union[str, Sequence[str], None] = '344adc5da83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_snapshots',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True, comment='Run ID, null for seed content'),
    sa.Column('content_uid', sa.String(), nullable=False, comment='UID from hive ContentDatabase'),
    sa.Column('content_text', sa.String(), nullable=False, comment='Actual code content as text'),
    sa.Column('parent_uid', sa.String(), nullable=True, comment='Parent content UID (null for seed)'),
    sa.Column('co_parent_uids', sa.JSON(), nullable=True, comment='List of co-parent UIDs for crossover'),
    sa.Column('fitness', sa.JSON(), nullable=True, comment='Multi-dimensional fitness values'),
    sa.Column('evaluation', sa.JSON(), nullable=True, comment='Full evaluation results'),
    sa.Column('metainfo', sa.JSON(), nullable=True, comment='Additional metadata for the content snapshot'),
    sa.Column('language', sa.String(), nullable=True, comment='Programming language for syntax highlighting'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_del', sa.Integer(), nullable=True, comment='0 for not deleted, 1 for deleted'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_content_snapshots_trial_id', 'content_snapshots', ['trial_id'], unique=False)
    op.create_index('ix_content_snapshots_trial_id_is_del', 'content_snapshots', ['trial_id', 'is_del'], unique=False)
    op.create_table('image_build_cache',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA256 hex digest'),
    sa.Column('image_type', sa.String(length=20), nullable=False, comment="'base' or 'sandbox'"),
    sa.Column('image_name', sa.String(length=500), nullable=False, comment='Full image URL'),
    sa.Column('inputs_summary', sa.JSON(), nullable=True, comment='Debug info about hash inputs'),
    sa.Column('hit_count', sa.Integer(), nullable=True, comment='Number of cache hits'),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True, comment='Last cache hit'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Integer(), nullable=True, comment='1 for valid, 0 for invalidated'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_image_build_cache_hash', 'image_build_cache', ['content_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_build_cache_hash', table_name='image_build_cache')
    op.drop_table('image_build_cache')
    op.drop_index('ix_content_snapshots_trial_id_is_del', table_name='content_snapshots')
    op.drop_index('ix_content_snapshots_trial_id', table_name='content_snapshots')
    op.drop_table('content_snapshots')
    # ### end Alembic commands ###
