"""add indexes for image_build_cache and content_snapshots

Revision ID: f23c33ff866a
Revises: c2eb3f1f9b97
Create Date: 2026-03-02 13:03:24.053563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23c33ff866a'
down_revision: Union[str, Sequence[str], None] = 'c2eb3f1f9b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_snapshots_experiment_id_content_uid', 'content_snapshots', ['experiment_id', 'content_uid'], unique=False)
    op.create_index('ix_content_snapshots_experiment_id_created_at', 'content_snapshots', ['experiment_id', 'created_at'], unique=False)
    op.create_index('ix_content_snapshots_experiment_id_is_del', 'content_snapshots', ['experiment_id', 'is_del'], unique=False)
    op.create_index('ix_content_snapshots_team_id', 'content_snapshots', ['team_id'], unique=False)
    op.create_index('idx_experiment_label_lookup', 'experiment_labels', ['experiment_id', 'label_name', 'label_value'], unique=False)
    op.create_index('idx_experiment_team_active_time', 'experiments', ['team_id', 'is_del', 'created_at'], unique=False)
    op.create_index('idx_experiment_team_name', 'experiments', ['team_id', 'name', 'is_del'], unique=False)
    op.create_index('ix_image_build_cache_last_hit_at', 'image_build_cache', ['last_hit_at'], unique=False)
    op.create_index('ix_image_build_cache_type_valid', 'image_build_cache', ['image_type', 'is_valid'], unique=False)
    op.create_index('idx_metric_experiment_time', 'metrics', ['experiment_id', 'created_at'], unique=False)
    op.create_index('idx_metric_run_time', 'metrics', ['run_id', 'created_at'], unique=False)
    op.create_index('idx_run_experiment_active', 'runs', ['experiment_id', 'is_del', 'created_at'], unique=False)
    op.create_index('idx_run_team_active', 'runs', ['team_id', 'is_del'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index('idx_run_team_active', table_name='runs')
    op.drop_index('idx_run_experiment_active', table_name='runs')
    op.drop_index('idx_metric_run_time', table_name='metrics')
    op.drop_index('idx_metric_experiment_time', table_name='metrics')
    op.drop_index('ix_image_build_cache_type_valid', table_name='image_build_cache')
    op.drop_index('ix_image_build_cache_last_hit_at', table_name='image_build_cache')
    op.drop_index('idx_experiment_team_name', table_name='experiments')
    op.drop_index('idx_experiment_team_active_time', table_name='experiments')
    op.drop_index('idx_experiment_label_lookup', table_name='experiment_labels')
    op.drop_index('ix_content_snapshots_team_id', table_name='content_snapshots')
    op.drop_index('ix_content_snapshots_experiment_id_is_del', table_name='content_snapshots')
    op.drop_index('ix_content_snapshots_experiment_id_created_at', table_name='content_snapshots')
    op.drop_index('ix_content_snapshots_experiment_id_content_uid', table_name='content_snapshots')
    # ### end Alembic commands ###
