"""add new table tags

Revision ID: faa471d8accb
Revises: 467107424ef6
Create Date: 2026-03-12 23:51:17.473606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa471d8accb'
down_revision: Union[str, Sequence[str], None] = '467107424ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_experiment_tag'), 'experiment_tags', type_='unique')
    op.create_index('idx_experiment_tag_lookup', 'experiment_tags', ['experiment_id', 'tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_experiment_tag_lookup', table_name='experiment_tags')
    op.create_unique_constraint(op.f('unique_experiment_tag'), 'experiment_tags', ['experiment_id', 'tag'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
