"""add usage and cost fields

Revision ID: fd4984c761c2
Revises: 0f417c7cf4d3
Create Date: 2026-03-07 09:24:35.803615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4984c761c2'
down_revision: Union[str, Sequence[str], None] = '0f417c7cf4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('usage', sa.JSON(), nullable=True, comment='The usage information, e.g. for LLM calls:             {total_tokens: int, input_tokens: int, output_tokens: int}'))
    op.add_column('experiments', sa.Column('cost', sa.JSON(), nullable=True, comment='Cost of the run in dollars'))
    op.add_column('runs', sa.Column('usage', sa.JSON(), nullable=True, comment='The usage information, e.g. for LLM calls:             {total_tokens: int, input_tokens: int, output_tokens: int}'))
    op.add_column('runs', sa.Column('cost', sa.JSON(), nullable=True, comment='Cost of the run in dollars'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'cost')
    op.drop_column('runs', 'usage')
    op.drop_column('experiments', 'cost')
    op.drop_column('experiments', 'usage')
    # ### end Alembic commands ###
